apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: sonuu23/node-mongo-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://admin:password@mongo-service:27017/?authSource=admin

